### PR TITLE
add lambda_lanczos files

### PR DESCRIPTION
**Pull request by mrcdr**
Hello Jacob,

As Andrew mentioned last week ([Github comment here](https://github.com/mrcdr/lambda-lanczos/commit/9e0123953f1c06dc6ceb3df0d402c51ee38ecb51#commitcomment-36097194)), I added my eigen code to src/USER_MISC.
I haven't put license statement (GPL/MIT dual license) to the files yet.
If I should do it by myself, please tell me to do so.

Thank you,

### CODE REVIEW

**Comment by jewettaij** [comment]
Great.  Thanks!  I finally ironed all of the syntax errors out of my code.  It compiles now.  Once it's working, I'll issue a pull request to add my code too.

**Comment by jewettaij** [comment]
I'll wait until Jacob merges the pull request before I add my changes.
Jacob, I have a question for you:

Do you want me to absorb everything into "fix_bond_react.h"?, or do you want to have separate files for the eigenvector calculator ("lambda_lanczos.hpp", 621 lines) and superimposing molecules ("superpose3d.hpp", 500 lines), and your code ("fix_bond_react.h").  If we keep the files separate, we could rename them ("fix_bond_react_eigen_utils.h", "fix_bond_react_superpose.h"?)
I don't care.  It's up to you.

Incidentally, I doubt this matters to you but Yuya requested that any file containing his code must be made available under both the GPL and MIT licenses (a "[dual license](https://opensource.stackexchange.com/questions/4606/implication-of-lgpl-and-mit-licenses-for-commercial-use-of-jsxgraph-library)".  This is a 2-line change to the header of the file.  I don't think Steve or Axel will mind or even notice, especially if it's not in the main file that you wrote.  Unlike Eigen which uses the MPL license, the MIT license is almost the least restrictive license there is.  I can't imagine Axel or Steve objecting to this change, because [adding the MIT license to one of the files because this does not restrict the LAMMPS developers if they want to change the license LAMMPS uses to something else later](https://github.com/mrcdr/lambda-lanczos/commit/9e0123953f1c06dc6ceb3df0d402c51ee38ecb51#commitcomment-36097194).  And I don't plan on asking them for permission this time either.)

**Comment by jewettaij** [comment]
At long last, the code for superimposing 2 point clouds is working.
It uses the two files that Yuya added with this pull request.
I will send a pull request with my files today.

Incidentally, you will have to modify this line in *lambda_lancozs.hpp*
```
#include <lambda_lanczos/lambda_lanczos_utils.h>
```
because you will probably want to move that file out of the *lambda_lanczos* subdirectory.

**Comment by mrcdr** [comment]
As Andrew mentioned 2 weeks ago, it's better for my code to be included via his branch.
I close this pull request.

Thank you,

**Pull request closed without merging**
